#!/bin/bash
# Summarize exit-node kernel flow logs generated by enable-exit-node-audit.sh

set -euo pipefail

LOG_PREFIX="${LOG_PREFIX:-OC_EGRESS}"
WINDOW_MINUTES="${WINDOW_MINUTES:-60}"
FLOW_LOG_PATH="${FLOW_LOG_PATH:-/var/log/openclaw/egress-flow.log}"
STAMP="$(date +%Y%m%d_%H%M%S)"
OUT_DIR="${OUT_DIR:-/var/log/openclaw/audit}"
OUT_FILE="$OUT_DIR/exit-node-audit-$STAMP.txt"

mkdir -p "$OUT_DIR"

if [[ ! -f "$FLOW_LOG_PATH" ]]; then
    if command -v journalctl &> /dev/null; then
        journalctl -k --since "-$WINDOW_MINUTES min" | grep "$LOG_PREFIX" > "$OUT_FILE" || true
    else
        echo "No flow log file found and journalctl unavailable." > "$OUT_FILE"
    fi
else
    if date -v-1M +%s >/dev/null 2>&1; then
        SINCE_EPOCH="$(date -v-"$WINDOW_MINUTES"M +%s)"
    else
        SINCE_EPOCH="$(date -d "-$WINDOW_MINUTES minutes" +%s)"
    fi
    awk -v since="$SINCE_EPOCH" '
    {
        if (match($0, /SRC=([0-9.]+)/, m)) src = m[1]; else src = "unknown"
        if (match($0, /DST=([0-9.]+)/, m)) dst = m[1]; else dst = "unknown"
        if (match($0, /DPT=([0-9]+)/, m)) dpt = m[1]; else dpt = "unknown"
        key = src " -> " dst ":" dpt
        count[key]++
    }
    END {
        for (k in count) {
            print count[k] "\t" k
        }
    }' "$FLOW_LOG_PATH" | sort -nr > "$OUT_FILE"
fi

echo "Exit-node audit report written: $OUT_FILE"
